insert into COURSES
(CODE,DESCRIPTION,CATEGORY,DURATION)
VALUES
('JAV','Java for Oracle','developers','BLD',4);-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-09-12 23:07:52.594

-- tables
-- Table: COURSES
CREATE TABLE COURSES (
    CODE varchar2(6)  NOT NULL,
    DESCRIPTION varchar2(30)  NULL,
    CATEGORY char(3)  NULL,
    DURATION number(2)  NULL,
    CONSTRAINT COURSES_pk PRIMARY KEY (CODE)
) ;

-- Table: DEPARTMENTS
CREATE TABLE DEPARTMENTS (
    DEPTINO number(2)  NOT NULL,
    DNAME varchar2(10)  NULL,
    LOCATION varchar2(8)  NULL,
    MGR number(4)  NOT NULL,
    CONSTRAINT DEPARTMENTS_pk PRIMARY KEY (DEPTINO)
) ;

-- Table: EMPLOYEES
CREATE TABLE EMPLOYEES (
    EMPNO number(4)  NOT NULL,
    ENAME varchar2(8)  NOT NULL,
    INIT varchar2(5)  NOT NULL,
    JOB varchar2(8)  NOT NULL,
    MGR number(4)  NOT NULL,
    BDATE date  NOT NULL,
    MSAL number(6,2)  NOT NULL,
    COMM number(6,2)  NOT NULL,
    DEPTNO number(2)  NOT NULL,
    CONSTRAINT EMPLOYEES_pk PRIMARY KEY (EMPNO)
) ;

-- Table: HISTORY
CREATE TABLE HISTORY (
    EMPNO number(4)  NOT NULL,
    BEGINYEAR number(4)  NULL,
    BEGINDATE date  NOT NULL,
    ENDDATE date  NOT NULL,
    DEPTINO number(2)  NOT NULL,
    MSAL number(6,2)  NULL,
    COMMENTS varchar2(60)  NOT NULL,
    CONSTRAINT HISTORY_pk PRIMARY KEY (EMPNO,BEGINDATE)
) ;

-- Table: OFFERINGS
CREATE TABLE OFFERINGS (
    COURSE varchar2(6)  NOT NULL,
    BEGINDATE date  NOT NULL,
    TRAINER number(4)  NOT NULL,
    LOCATION varchar2(8)  NOT NULL,
    CONSTRAINT OFFERINGS_pk PRIMARY KEY (COURSE,BEGINDATE)
) ;

-- Table: REGISTRATIONS
CREATE TABLE REGISTRATIONS (
    ATTENDEE number(4)  NOT NULL,
    COURSE varchar2(6)  NOT NULL,
    BEGINDATE date  NOT NULL,
    EVALUATION number(1)  NOT NULL,
    CONSTRAINT REGISTRATIONS_pk PRIMARY KEY (ATTENDEE,COURSE,BEGINDATE)
) ;

-- Table: SALGRADES
CREATE TABLE SALGRADES (
    GRADE number(2)  NOT NULL,
    LOWERLIMIT number(6,2)  NULL,
    UPPERLIMIT number(6,2)  NULL,
    BONUS number(6,2)  NULL,
    CONSTRAINT SALGRADES_pk PRIMARY KEY (GRADE)
) ;

-- foreign keys
-- Reference: DEPARTMENTS_EMPLOYEES (table: DEPARTMENTS)
ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPARTMENTS_EMPLOYEES
    FOREIGN KEY (MGR)
    REFERENCES EMPLOYEES (EMPNO);

-- Reference: EMPLOYEES_DEPARTMENTS (table: EMPLOYEES)
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_DEPARTMENTS
    FOREIGN KEY (DEPTNO)
    REFERENCES DEPARTMENTS (DEPTINO);

-- Reference: EMPLOYEES_EMPLOYEES (table: EMPLOYEES)
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_EMPLOYEES
    FOREIGN KEY (MGR)
    REFERENCES EMPLOYEES (EMPNO);

-- Reference: HISTORY_DEPARTMENTS (table: HISTORY)
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_DEPARTMENTS
    FOREIGN KEY (DEPTINO)
    REFERENCES DEPARTMENTS (DEPTINO);

-- Reference: HISTORY_EMPLOYEES (table: HISTORY)
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_EMPLOYEES
    FOREIGN KEY (EMPNO)
    REFERENCES EMPLOYEES (EMPNO);

-- Reference: OFFERINGS_COURSES (table: OFFERINGS)
ALTER TABLE OFFERINGS ADD CONSTRAINT OFFERINGS_COURSES
    FOREIGN KEY (COURSE)
    REFERENCES COURSES (CODE);

-- Reference: OFFERINGS_EMPLOYEES (table: OFFERINGS)
ALTER TABLE OFFERINGS ADD CONSTRAINT OFFERINGS_EMPLOYEES
    FOREIGN KEY (TRAINER)
    REFERENCES EMPLOYEES (EMPNO);

-- Reference: REGISTRATIONS_EMPLOYEES (table: REGISTRATIONS)
ALTER TABLE REGISTRATIONS ADD CONSTRAINT REGISTRATIONS_EMPLOYEES
    FOREIGN KEY (ATTENDEE)
    REFERENCES EMPLOYEES (EMPNO);

-- Reference: REGISTRATIONS_OFFERINGS (table: REGISTRATIONS)
ALTER TABLE REGISTRATIONS ADD CONSTRAINT REGISTRATIONS_OFFERINGS
    FOREIGN KEY (COURSE,BEGINDATE)
    REFERENCES OFFERINGS (COURSE,BEGINDATE);

-- End of file.



('JAV','Java for Oracle','developers','BLD',4);


PLS','Introduction to PL/SQL BLD 1
XML','XML for Oracle developers BLD 2
ERM','Data modeling with ERM DSG 3
GEN','System generation DSG 4
PMT','Process modeling techniques DSG 1
PRO','Prototyping DSG 5
RSD','Relational system design DSG 2
OAU','Oracle for application users GEN 1'
SQL','Introduction to SQL','GEN','4');